#Configuration de la base de données.
bdd:
  driver: jdbc:mysql
  host: localhost
  port: 3306
  database: ec4wdw13erizia
  user: dimdim
  pass: Dimitri11!
  table: pf8kr9g9players
  #Utilisateur de la base de données qui n'as que les droits SELECT et UPDATE sur les tables.
  user_select_update:
  pass_select_update:
  #Utilisateur de la base de données qui n'as que les droits SELECT et INSERT sur les tables.
  user_select_insert:
  pass_select_insert:
  #Utilisateur de la base de données qui n'as que les droits SELECT sur les tables.
  user_select:
  pass_select:

#Salage pour l'algorithme sha 256 à modifier au lancement du serveur et ne jamais le remodifier. Sinon corruption des mots de passe de la base de données.
security:
  sel: ec4wdw13
 
#Message d'exclusion du serveur.
string_kick:
  #Avant la connection d'un joueur.
  ip: Ip trop de fois similaire pour plusiseurs personne.
  online: Joueur deja en ligne.
  ban: Tu es Bannie.
  #Pendant l'enregistrement ou l'identification d'un joueur.
  over_time: Tu as étais exclue pour inactivité.

#Message d'entré plus le temps avant enregistrement dans le serveur.
string:
  register_title: Bienvenue !
  register_subtitles: Enregistre toi -> /register !
  register_time: 120
#Message d'entré plus le temps avant identification dans le serveur.
  login_title: Salut !
  login_subtitles: Identifie toi -> /login  !
  login_time: 120
#Message d'erreur des commande.
  error_register_pass: Le mot de passe dois faire au mini 8 caractère ou ce corresponde pas.
  error_register: Tu es déja enregister , utilise la commande /login [pass] pour d'identifier.
  error_login_pass: Le mot de passe est incorecte.
  error_login: Tu n'es pas enregistrer, utilise la commande /register pour t'enregistrer.
#Message après identification durée de une seconde.
  after_login_title: Bienvenue !
  after_login_subtitles: Tu es bien identifier !
