bdd:
  url: jdbc:mysql://
  host: localhost:3306/
  user: root
  pass: root
  database: spigot


Connection:
  titre: Bienvenue !
  soustitre: Enregistre toi !
  message_kick: Tu as étais exclue pour inactivité.
  temps_enregistrement: 120
