bdd:
  driver: jdbc:mysql
  host: localhost
  port: 3306
  database: spigot
  user: dimdim
  pass: Dimitri11!
  

Connection:
  titre: Bienvenue !
  soustitre: Enregistre toi !
  message_kick: Tu as étais exclue pour inactivité.
  temps_enregistrement: 120
