#Partie 1:Configuration de la base de données.
bdd:
  driver: jdbc:mysql
  host: localhost
  port: 3306
  database: ec4wdw13erizia
  user: dimdim
  pass: Dimitri11!
  table: pf8kr9g9players
  #Utilisateur de la base de données qui n'as que les droits SELECT et UPDATE sur les tables.
  user_select_update:
  pass_select_update:
  #Utilisateur de la base de données qui n'as que les droits SELECT et INSERT sur les tables.
  user_select_insert:
  pass_select_insert:
  #Utilisateur de la base de données qui n'as que les droits SELECT sur les tables.
  user_select:
  pass_select:

#Salage pour l'algorithme sha 256 et MD5 à modifier au lancement du serveur et ne jamais le remodifier. Sinon corruption des mots de passe de la base de données.
security:
  sel: ec4wdw13

##########################################################################
#Liste des codes couleur du tchat
# §4 "dark_red"
# §c "red"
# §6 "gold"
# §e "yellow"
# §2 "dark_green"
# §a "green"
# §b "aqua"
# §3 "dark_aqua"
# §1 "dark_blue"
# §9 "blue"
# §d "light_purple"
# §5 "dark_purple"
# §f "white"
# §7 "gray"
# §8 "dark_gray"
# §0 "black"
# §r "reset" Réinitialise la couleur par défaut
# §l "Gras"
# §o "Italic"
# §n "Souligné"
# §m "Barré"

# Exemple d'utilisation:
# ip: §cIp trop de fois similaire pour plusiseurs personne.
# On utilise §c devant le message et celui-ci sera en "rouge".

########################################################################## 
#Personnalisation des messages d'exclusion, d'enregistrement,
#d'identification et des commandes ainsi que leurs configurations.
 
#Partie 2:Message d'exclusion du serveur et configuration.
string_kick:
  #Avant la connection d'un joueur.
  ip: Ip trop de fois similaire pour plusiseurs personne.
  online: Joueur deja en ligne.
  ban: Tu es Bannie.
  #Pendant l'enregistrement ou l'identification d'un joueur.
  over_time: Tu as étais exclue pour inactivité.
  #Nombre d'ip similaire connecter à la fois au serveur.
  over_ip: 2

##########################################################################

#Partie 3:Message d'entré plus le temps avant enregistrement dans le serveur.
string:
  register_title: Bienvenue !
  register_subtitles: Enregistre toi -> /register !
  register_time: 120

##########################################################################

#Partie 4:Message d'entré plus le temps avant identification dans le serveur.
  login_title: Salut !
  login_subtitles: Identifie toi -> /login  !
  login_time: 120

##########################################################################

#Partie 4:Message d'erreur des commande.
  error_register_pass: Le mot de passe dois faire au mini 8 caractère ou ce corresponde pas.
  error_register: Tu es déja enregister , utilise la commande /login [pass] pour d'identifier.
  error_login_pass: Le mot de passe est incorecte.
  error_login: Tu n'es pas enregistrer, utilise la commande /register pour t'enregistrer.

##########################################################################

#Partie 5: Message après identification durée de une seconde.
  after_login_title: Bienvenue !
  after_login_subtitles: Tu es bien identifier !

##########################################################################

#Partie 6: Message commande unban.
  bannie: §c
  already: §c
