bdd:
  driver: jdbc:mysql
  host: localhost
  port: 3306
  database: ec4wdw13erizia
  user: dimdim
  pass: Dimitri11!

Connection:
  message_kick: Tu as étais exclue pour inactivité.
  titre_enregistrement: Bienvenue !
  soustitre_enregistrement: Enregistre toi -> /register !
  temps_enregistrement: 120
  temps_indentification: 120
  titre_indentification: "Salut !"
  soustitre_indentification: "Identifie toi -> /login  !"
  