main: fr.loirelique.lpsecurity.Main
name: LPsecurity
version: 1.0
description: Ce plugin incorport la sécurité du serveur au niveau des joueurs et de leurs compte utilisateur ainsi qu'une partie sanction.
author: LoiRelique



commands:
  register:
    description: Permet d'enregister son mdp à la premiere connection.(LPsecurity)
    usage: §e/register [pass] [pass]
    permission: lpsecurity.register

  login:
    description: Permet de s'identifer au serveur.(LPsecurity)
    usage: §e/login [pass]
    permission: lpsecurity.login

  ban:
    description: Description de la commande.(LPsecurity)
    usage: §e/ban [Nom du joueur] [Raison]
    permission: lpsecurity.ban

  tempban:
    description: Description de la commande.(LPsecurity)
    usage: §e/tempban [Nom du joueur] [Temps <Année> <Mois> <Jours> <Heures> <Minutes>] [Raison]
    permission: lpsecurity.tempban  
  
  unban:
    description: Description de la commande.(LPsecurity)
    usage: §§e/unban [Nom du joueur] [Raison]
    permission: lpsecurity.unban

  resethistorique:
    description: Description de la commande.(LPsecurity)
    usage: §e/resethistorique [Nom du joueur]
    permission: lpsecurity.resethistorique

  historique:
    description: Description de la commande.(LPsecurity)
    usage: §e/historique [Nom du joueur]
    permission: lpsecurity.historique
  
  mute:
    description: Description de la commande.(LPsecurity)
    usage: §e/mute [Nom du joueur] [Raison]
    permission: lpsecurity.mute

  tempmute:
    description: Description de la commande.(LPsecurity)
    usage: §e/tempmute [Nom du joueur] [Temps <Année> <Mois> <Jours> <Heures> <Minutes>] [Raison]
    permission: lpsecurity.tempmute
  
  unmute:
    description: Description de la commande.(LPsecurity)
    usage: §e/unmute [Nom du joueur] [Raison]
    permission: lpsecurity.unmute
  
  kick:
    description: Description de la commande.(LPsecurity)
    usage: §e/kick [Nom du joueur] [Raison]
    permission: lpsecurity.kick

permissions:
  lpsecurity.login:
    description: permet d'utiliser la commande login.(LPsecurity)
    default: true

  lpsecurity.register:
    description: permet d'utiliser la commande register.(LPsecurity)
    default: true

  lpsecurity.ban:
    description: permet d'utiliser les commande ban.(LPsecurity)
    default: true

  lpsecurity.tempban:
    description: permet d'utiliser les commande tempban.(LPsecurity)
    default: true

  lpsecurity.unban:
    description: permet d'utiliser les commande unban.(LPsecurity)
    default: true

  lpsecurity.resethistorique:
    description: permet d'utiliser les commande resethistorique.(LPsecurity)
    default: true
  
  lpsecurity.historique:
    description: permet d'utiliser les commande historique.(LPsecurity)
    default: true
  
  lpsecurity.mute:
    description: permet d'utiliser les commande mute.(LPsecurity)
    default: true

  lpsecurity.tempmute:
    description: permet d'utiliser les commande tempmute.(LPsecurity)
    default: true
  
  lpsecurity.unmute:
    description: permet d'utiliser les commande unmute.(LPsecurity)
    default: true

  lpsecurity.kick:
    description: permet d'utiliser les commande kick.(LPsecurity)
    default: true
    
