main: fr.loirelique.lpsecurity.Main
name: LPsecurity
version: 1.0
description: Ce plugin incorport la sécurité du serveur au niveau des joueurs et de leurs compte utilisateur ainsi que des permission et commande en rapport avec la sécurité.
author: LoiRelique

