main: fr.loirelique.lpsecurity.Main
name: LPsecurity
version: 1.0
description: Ce plugin incorport la sécurité du serveur au niveau des joueurs et de leurs compte utilisateur ainsi qu'une partie sanction.
author: LoiRelique



commands:
  register:
    description: Permet d'enregister son mdp à la premiere connection.(LPsecurity)
    usage: /register [pass] [pass]
    permission: LP.security.register

  login:
    description: Permet de s'identifer au serveur.(LPsecurity)
    usage: /login [pass]
    permission: LP.security.login

  ban:
    description: Description de la commande.(LPsecurity)
    usage: /ban [Nom du joueur] [Raison]
    permission: LP.security.ban

  tempban:
    description: Description de la commande.(LPsecurity)
    usage: /tempban [Nom du joueur] [Temps <Année> <Mois> <Jours> <Heures> <Minutes>] [Raison]
    permission: LP.security.tempban  
  
  unban:
    description: Description de la commande.(LPsecurity)
    usage: /unban [Nom du joueur] [Raison]
    permission: LP.security.unban

permissions:
  LP.security.login:
    description: permet d'utiliser la commande login.(LPsecurity)
    default: true

  LP.security.register:
    description: permet d'utiliser la commande register.(LPsecurity)
    default: true

  LP.security.ban:
    description: permet d'utiliser les commande ban.(LPsecurity)
    default: true

  LP.security.tempban:
    description: permet d'utiliser les commande tempban.(LPsecurity)
    default: true

  LP.security.unban:
    description: permet d'utiliser les commande unban.(LPsecurity)
    default: true