main: fr.loirelique.lpsecurity.Main
name: LPsecurity
version: 1.0
description: Ce plugin incorport la sécurité du serveur au niveau des joueurs et de leurs compte utilisateur ainsi qu'une partie sanction.
author: LoiRelique



commands:
  register:
    description: Permet d'enregister son mdp à la premiere connection.
    usage: /register [pass] [pass]
    permission: LP.security.register

  login:
    description: Permet de s'identifer au serveur.
    usage: /login [pass]
    permission: LP.security.login

  banish:
    description: Description de la commande.
    usage: /banish [Nom du joueur] [1|0]
    permission: LP.security.ban

  ban:
    description: Description de la commande.
    usage: /ban [Nom du joueur] [Raison] (LPsecurity)
    permission: LP.security.ban

  tempban:
    description: Description de la commande.
    usage: /tempban [Nom du joueur] [Temps] [Raison] (LPsecurity)
    permission: LP.security.ban  
  
  unban:
    description: Description de la commande.
    usage: /unban [Nom du joueur] [Raison] (LPsecurity)
    permission: LP.security.ban

permissions:
  LP.security.login:
    description: permet d'utiliser la commande login.
    default: true

  LP.security.register:
    description: permet d'utiliser la commande register.
    default: true

  LP.security.ban:
    description: permet d'utiliser les commande banish.
    default: true